- name: Retrieve vault password
  hosts: localhost
  connection: local
  tasks:
    - name: Get secret KV
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=demo/data/ssh:username token={{ token }} url=http://vault.rdevopsb84.online:8200') }}"

