- name: Retrieve vault password
  hosts: localhost
  connection: local
  tasks:
    - name: Get secret KV
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.vault_kv2_get', 'demo', token='{{ token }}', url='http://vault.rdevopsb84.online:8200') }}"

