- name: Retrieve vault password
  hosts: localhost
  connection: local
  tasks:
    - name: Get secret KV
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.vault_kv2_get', 'demo', token='{{ token }}', url='https://vault:8201') }}"

