- name: Docker
  hosts: localhost
  connection: local
  tasks:
    - name: Nginx container
      community.docker.docker_container:
        name: nginx-sample
        image: docker.io/nginx
        state: started
        ports:
          - "8080:80"

